// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package housework

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RobotMaidClient is the client API for RobotMaid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RobotMaidClient interface {
	Add(ctx context.Context, in *Chores, opts ...grpc.CallOption) (*Response, error)
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*Response, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Chores, error)
}

type robotMaidClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotMaidClient(cc grpc.ClientConnInterface) RobotMaidClient {
	return &robotMaidClient{cc}
}

func (c *robotMaidClient) Add(ctx context.Context, in *Chores, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/housework.RobotMaid/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotMaidClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/housework.RobotMaid/Complete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotMaidClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Chores, error) {
	out := new(Chores)
	err := c.cc.Invoke(ctx, "/housework.RobotMaid/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RobotMaidServer is the server API for RobotMaid service.
// All implementations must embed UnimplementedRobotMaidServer
// for forward compatibility
type RobotMaidServer interface {
	Add(context.Context, *Chores) (*Response, error)
	Complete(context.Context, *CompleteRequest) (*Response, error)
	List(context.Context, *Empty) (*Chores, error)
	mustEmbedUnimplementedRobotMaidServer()
}

// UnimplementedRobotMaidServer must be embedded to have forward compatible implementations.
type UnimplementedRobotMaidServer struct {
}

func (UnimplementedRobotMaidServer) Add(context.Context, *Chores) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedRobotMaidServer) Complete(context.Context, *CompleteRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedRobotMaidServer) List(context.Context, *Empty) (*Chores, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedRobotMaidServer) mustEmbedUnimplementedRobotMaidServer() {}

// UnsafeRobotMaidServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotMaidServer will
// result in compilation errors.
type UnsafeRobotMaidServer interface {
	mustEmbedUnimplementedRobotMaidServer()
}

func RegisterRobotMaidServer(s *grpc.Server, srv RobotMaidServer) {
	s.RegisterService(&_RobotMaid_serviceDesc, srv)
}

func _RobotMaid_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chores)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotMaidServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/housework.RobotMaid/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotMaidServer).Add(ctx, req.(*Chores))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotMaid_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotMaidServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/housework.RobotMaid/Complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotMaidServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotMaid_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotMaidServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/housework.RobotMaid/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotMaidServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _RobotMaid_serviceDesc = grpc.ServiceDesc{
	ServiceName: "housework.RobotMaid",
	HandlerType: (*RobotMaidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _RobotMaid_Add_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _RobotMaid_Complete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _RobotMaid_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "housework.proto",
}
